#******** DO NOT EDIT THIS FILE ********#
# make csc2035 assignment2 network project
SHELL = /bin/sh

CC ?= cc

CFLAGS := -Wall

# may have to edit the following if not on Linux or MacOS
os := $(shell uname)
ifeq ($(os),Linux)
    CFLAGS +=-g -std=c99 -D_GNU_SOURCE
endif

all: clean rft_client rft_server
.PHONY: all

clean:
	-rm -f rft_client
	-rm -f rft_server
	-rm -f *.o
.PHONY: clean

rft_client: rft_client.c rft_util.o  rft_client_util.o

rft_server: rft_server.c rft_util.o




