#include <stdio.h>
#include <string.h>
#include <errno.h>
#include "rft_util.h"
#include <stdlib.h>


/* Utility functions - do NOT edit this file */

int checksum(char* payload, bool is_corrupted) {
    if (is_corrupted)
        return -rand();
    
    int sum = 0;
    
    for (int i = 0; i < PAYLOAD_SIZE; i++)
        sum += payload[i];

    return sum;
}

void print_sep() {
    printf("----------------------------------------------------------"
            "---------------------\n");
}

void print_msg(char* role, char* msg) {
    printf("%s: %s\n", role, msg);
}

void print_err(char* role, int line, char* msg) {
    fprintf(stderr, "%s: [line %d] %s - %s\n", role, line, 
            msg, strerror(errno));
}
